services:
  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - app_network
    ports:
      - "2604:2604"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - app_network
    ports:
      - "4813:3000"

networks:
  app_network:
    driver: bridge
